name: Build LaTeX document
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: lualatex main
        uses: dante-ev/latex-action@latest
        continue-on-error: true
        with:
          root_file: ConjureIgnanMephitLevel2.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape
      - name: lualatex main 2
        uses: dante-ev/latex-action@latest
        continue-on-error: true
        with:
          root_file: ConjureIgnanMephitLevel2.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape
      - name: Upload the PDF
        uses: actions/upload-artifact@v4
        with:
          name: spell-card
          path: |
            ./ConjureIgnanMephitLevel2.pdf
            ./ConjureIgnanMephitLevel2.log